# build docker compose for laravel app 
# php 8.1 

version: '3.9'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db
        networks:
            - laravel



# mysql v8.0.0 
    db:
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_ROOT: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - laravel
      

# Adminer to manage MySQL
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - laravel

# Docker volume for MySQL Data
volumes:
    dbdata:

# Only Laravel, and Adminer are exposed to public network
networks:
    laravel:
        driver: bridge
        












