version: "3.9"
services:
  app:
    build:
      args:
        user: nabil
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db:
    image: mysql:8.0
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - travellist
  
  adminer:
    image: adminer
    container_name: travellist-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - travellist

volumes:
  mysql:
    driver: local

networks:
  travellist:
    driver: bridge